MODULES=(loop squashfs iso9660)
BINARIES=()
FILES=(/etc/systemd/system/initrd-lrescue-root.service)
HOOKS=(base systemd modconf block filesystems)
COMPRESSION="xz"
COMPRESSION_OPTIONS=(-9)
MODULES_DECOMPRESS="yes"
