MODULES=(loop squashfs iso9660 sr_mod cdrom ahci ata_piix)
BINARIES=()
FILES=(
	/etc/systemd/system/initrd-lrescue-root.service
	/etc/systemd/system/initrd-root-fs.target.wants/initrd-lrescue-root.service
	/etc/passwd
	/etc/shadow
)
HOOKS=(base systemd modconf block filesystems)
COMPRESSION="xz"
COMPRESSION_OPTIONS=(-9)
MODULES_DECOMPRESS="yes"
